### ISSUE TITLE
Bulk convert entire directory

### ISSUE THREAD

**Issue by iApeiron** [libimobiledevice/libplist#106]
Using apple's default tool, "plutil -convert binary1 *.plist" for example, will convert all plists in the current directory.
Using a * wildcard with plistutil, on the other hand, seems to only interact with the first plist in the list.

Is this the intended behaviour of plistutil? Is there an easy way to bulk convert an entire directory?

Thanks.

**Comment by nikias** [comment]
Bulk converting isn't supported and I don't see any reason to, because you can just use a bash loop:
```
for I in *.plist; do plutil -i $I -o `basename $I`.bplist; done
```
Just be a little creative. Mind tht this would convert files from xml to binary or binary to xml, depending on the initial format.

**Comment by iApeiron** [comment]
Thank you.
