### ISSUE TITLE
Clang over GCC

### ISSUE THREAD

**Issue by top-sekret** [libimobiledevice/libplist#108]
Why is Clang preferred over GCC?

I always build libplist and other libimobiledevice with GCC. Most distros are suited for GCC. When building a package using automated tools, like debhelper, again, it chooses GCC.

So, why is Clang preferred?

**Comment by nikias** [comment]
This is because clang is used for adding AddressSanitizer and required to properly build libplist for fuzzing. If you want to compile with GCC, just pass CC=gcc CXX=g++ to ./autogen.sh or ./configure.
