### ISSUE TITLE
can any body help me to find which type of below plist??

### ISSUE THREAD

**Issue by ketan077** [libimobiledevice/libplist#115]
...............bplist00.........X$versionX$objectsY$archiverT$top........U$null_..setMaxConnectionEnqueue:_..NSKeyedArchiver...Troot.....#-27:@[mpu.............................

If i will decode above one then i'm creating my own plist and convert to binary plist seems different output i got

...............bplist00.........Y$archiver_..NSKeyedArchiverX$objects...U$null_..setMaxConnectionEnqueue:T$top...Troot..X$version........-69?Z_bgir...............................w

what's difference ??

**Comment by Pfm33** [comment]
[Archivo 13-12-24, 9 12 12 pm.txt](https://github.com/user-attachments/files/18135978/Archivo.13-12-24.9.12.12.pm.txt)
#
