### ISSUE TITLE
Remove or change libcnary's COPYING file

### ISSUE THREAD

**Issue by hadess** [libimobiledevice/libplist#119]
From what I can see, all the files under the libcnary directory are LGPLv2+ licensed, but the COPYING file says GPLv2. I can cook up a patch if we agree on the license. Is there an upstream for libcnary where this could be discussed and sorted out?

**Comment by nikias** [comment]
libcnary has it's own COPYING in the libcnary subfolder which says
```
GNU LESSER GENERAL PUBLIC LICENSE
Version 2.1, February 1999
```
so I don't think this is any issue here. We have COPYING and COPYING.LESSER in the main source tree. However in fact there are just two files, `m4/ax_pthread.m4` and `m4/ac_python_devel.m4` which both are GPLv3. Now I wonder if we should remove the main COPYING (which is GPLv2), rename COPYING.LESSER to COPYING and add _another_ COPYING with GPLv3 into m4 subdirectory ?!
