### ISSUE TITLE
It is recommended to add a function of plist_rename_key

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libplist#127]
In some places you need to change the key。

**Comment by nikias** [comment]
Can you give an example? Apple's CFDictionary API does not offer this feature so I don't see a reason to add it.
Also it can be done with removing an item from a dictionary and adding it with a different key.

**Comment by xdeng** [comment]
![20181116164357](https://user-images.githubusercontent.com/2641745/48609892-209d3880-e9bf-11e8-805c-0266dfe4cd15.jpg)

**Comment by xdeng** [comment]
and also  libplist memory usage is high
tinyxml2  read xml  memory usage 70M
pugixml  read xml  memory usage 50M

**Comment by xdeng** [comment]
@nikias    I tested the libxml version before.    I have not tested the new version.  If I have time, I will test it.

**Comment by xdeng** [comment]
@nikias  The memory usage is high because the leaf nodes have more data that is not used.

**Comment by nikias** [comment]
I added a new function `plist_dict_item_get_key()` that returns the key node for a given PLIST_DICT item. Example:
```
plist_t n = plist_dict_get_item(dict, "yeah");
plist_t key = plist_dict_item_get_key(n);
plist_set_key_val(key, "nope");
```
or in a classical iterator loop:
```
plist_t node = NULL;
do {
    node = NULL;
    char *key = NULL;
    plist_dict_next_item(dict, iter, &key, &node);
    if (key) {
        plist_t key_node = plist_dict_item_get_key(node);
        // decide wether to rename the key or not
        plist_set_key_val(key_node, "newkey");
        free(key);
    }
} while (node);
```
See commit ea37ed01b8c7e05078620ed039899ddff48eac1c.
