### ISSUE TITLE
plist_array_get_item_index  return 0 ?

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libplist#129]
```
PLIST_API uint32_t plist_array_get_item_index(plist_t node)
{
    plist_t father = plist_get_parent(node);
    if (PLIST_ARRAY == plist_get_node_type(father))
    {
        return node_child_position(father, node);
    }
    return 0;
}
```
return 0;   0  Is a valid value

    /**
     * Remove an existing position in a #PLIST_ARRAY node.
     * Removed position will be freed using #plist_free.
     *
     * @param node the node of type #PLIST_ARRAY
     * @param n The position to remove. Range is [0, array_size[. Assert if n is not in range.
     */
    void plist_array_remove_item(plist_t node, uint32_t n);

**Comment by xdeng** [comment]
```
PLIST_API uint32_t plist_array_get_item_index(plist_t node)
{
    plist_t father = plist_get_parent(node);
    if (PLIST_ARRAY == plist_get_node_type(father))
    {
        return node_child_position(father, node);
    }
    return -1;
}
```

**Comment by nikias** [comment]
This function basically only used by the C++ implementation. I changed the function to return UINT_MAX (0xFFFFFFFF) if the node index can't be determined. See commit 23e5a7636bba1565d000adcd4c3debc0788398c5.
