### ISSUE TITLE
Ancient typo in python version-detection

### ISSUE THREAD

**Issue by UnitedMarsupials** [libimobiledevice/libplist#134]
[FreeBSD ports](https://www.freshports.org/devel/libplist) have been applying this patch to `configure` for years. Because the packages on the [official web-site](http://www.libimobiledevice.org) are stale, I'm modifying the ports to fetch the latest code from GitHub instead. There is no `configure`, so the patch below patches the problem at the source:
```diff
--- m4/ac_python_devel.m4       2019-02-16 15:42:53.000000000 -0500
+++ m4/ac_python_devel.m4       2019-04-02 22:47:42.793789000 -0400
@@ -183,5 +183,5 @@
                        else
                                py_version=`$PYTHON -c "import sys; \
-                                       print(sys.version[[:3]]")`
+                                       print(sys.version[[:3]])"`
                        fi
                fi
```
The same diff needs to be applied to the same file in the libimobiledevice/libimobiledevice repo as well.

I do not understand, how this hasn't been detected/reported by others before, but better late than never... Thank you!

**Comment by nikias** [comment]
No idea how this never got noticed. Instead of this fix I updated the whole m4 file to the newer `ax_python_devel.m4`.
