### ISSUE TITLE
fatal error: 'cstddef' file not found [xcode 10, mojave]

### ISSUE THREAD

**Issue by wang111588** [libimobiledevice/libplist#135]
when I run ` $ brew install --HEAD usbmuxd `,  commend line show  these errors 

OS 10.14.4 (18E226)
xcode Version 10.2 (10E125),  NO xcode9

```
Last 15 lines from /Users/{user}/Library/Logs/Homebrew/usbmuxd/03.make:
/usr/local/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
collection.c#include <cstddef>
         ^~~~~~~~~
:27:
In file included from /usr/local/include/string.h:25:
/usr/local/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
make[1]: *** [collection.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -fvisibility=hidden -pthread -g -O2 -c thread.c -o thread.o >/dev/null 2>&1
1 error generated.
make[1]: *** [socket.lo] Error 1
make: *** [install-recursive] Error 1
```

I guess i need install libstdc++ or other library, but i don't kown  whar i need install and how i install them or  where put them.
other issue didn't solved my problem.
thanks a lot, my bad endlish~

**Comment by nikias** [comment]
The Xcode toolchain ships cstddef so I don't really understand why it can't find it...
```/Applications/Xcode.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef```

**Comment by nikias** [comment]
Try this: `xcode-select --install`, that should fix the issue.
