### ISSUE TITLE
Loss of precision when parsing or writing real values

### ISSUE THREAD

**Issue by dnicolson** [libimobiledevice/libplist#146]
Values of type `real` can lose precision if they contain more than 6 decimal places.  After using the `plist_test` binary, the value `8263.0072447640268` becomes `8263.007245` and the value `0.0` becomes `0.000000`.

The following commands:
```
git clone git@github.com:libimobiledevice/libplist.git
cd libplist
git checkout 072a31
./autogen.sh
make
cd test
./plist_test ~/precision-real.plist ~/precision-real-2.plist
```

Give the following output:
```
File /Users/dave/precision-real.plist is open
PList XML parsing succeeded
PList BIN writing succeeded
PList BIN parsing succeeded
PList XML writing succeeded
Size of input and output is different
Input size : 1155
Output size : 1139
```

[precision-real.plist.zip](https://github.com/libimobiledevice/libplist/files/3816826/precision-real.plist.zip)

**Comment by nikias** [comment]
Please check b7c802f1b7cdf8a271b148d4375c4309aefc5e0d. The input and output size will probably still differ, but it now handles 0.0 and the others cases like the official plutil tool.

**Comment by dnicolson** [comment]
This works correctly now and the output size is the same. The attached plist had some whitespace inconsistencies, running it through `plutil` twice and then `plist_test` produced the same file size.
