### ISSUE TITLE
Do you have a plan to merge libimobiledevice-win32/libplist to libimobiledevice/libplist

### ISSUE THREAD

**Issue by PhoebeHui** [libimobiledevice/libplist#147]
@qmfrederik, I noticed that libimobiledevice-win32/libplist contains some fixes for build issues on windows, that doesn't merge to libimobiledevice/libplist, do you have a plan to merge these changes?

**Comment by qmfrederik** [comment]
@PhoebeHui I'm all for merging the changes upstream, though it's up to @nikias to decide whether it's something he wants to do or not.
