### ISSUE TITLE
Problems of memory release in Win32

### ISSUE THREAD

**Issue by XanaduAPI** [libimobiledevice/libplist#172]
The following uses machine translation

In Win32, an exception is caused when one module provides memory and another module frees it.

So, can we consider adding plist_ free_ xml(void* _ XML) and plist_ free_ bin(void* _ bin) ?

I found that most of the mainstream open source libraries adopt this model.

**Comment by nikias** [comment]
See:
https://github.com/libimobiledevice/libplist/blob/master/include/plist/plist.h#L653
https://github.com/libimobiledevice/libplist/blob/master/include/plist/plist.h#L670

**Comment by XanaduAPI** [comment]
@nikias 
I'm sorry, I'm still using version 2.0.0, which has delayed your time.
