### ISSUE TITLE
Build fails with cython error?

### ISSUE THREAD

**Issue by SoPat712** [libimobiledevice/libplist#216]
![image](https://user-images.githubusercontent.com/30350506/205759892-df5d1807-ef2e-48bb-9d36-45691e4fdb11.png)

Tried building libimobiledevice-git on Manjaro, build failed. Realized that libplist-git was causing the problem. I tried to install from source using ./autogen.sh and make, but make keeps failing at the point screenshotted above.

Thanks for your help in advance.

I've tried changing python 3.10.7, 2.7.15, and 3.9.0, none of which have worked.

**Comment by alediaferia** [comment]
Changing to python3 fixed it for me. It was picking up a python2 bin I have installed too. Make sure you do

```shell
$ PYTHON=<path-to-your-python3-bin> ./autogen.sh
```

and try again.

**Comment by HMaker** [comment]
I had the same issue, I have ASDF which manages multiple python versions, to fix it I ran
```
PYTHON=/usr/bin/python3 ./autogen.sh
```
thanks @alediaferia
