### ISSUE TITLE
How to store negative integer

### ISSUE THREAD

**Issue by mveril** [libimobiledevice/libplist#217]
Hello
I currently work on [MobileDeviceSharp](https://github.com/mveril/MobileDeviceSharp) a C# object oriented wrapper around [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice) and there is something I don't understand. Normally integer value in Property list can be signed but you represent Integer plist node as uint64_t that is unsigned. This beaviour is reported in my C# implementation of the [PlistInteger](https://github.com/mveril/MobileDeviceSharp/blob/db6abce6a57bf3dd82a429c35fb0b5a06dcc71f2/src/MobileDeviceSharp/PropertyList/PlistInteger.cs) node. So what is the correct way to store signed integer property list value using this library.

**Comment by nikias** [comment]
Take a look at https://github.com/libimobiledevice/libplist/commit/d886885b0ec2506fa2caf0986a3d0e496fea91c2 .

**Comment by mveril** [comment]
Ok thank you for the reference From my point of view, it's going in the right direction because it's more consistent with the plist file format itself and I am happy about that. On my side I solve my issue using [UnmanagedType.U8](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedtype) to specify that on the C side the value is of type `uint64_t` even if on my side I use `long` value (`int64`) and it's work perfectly mveril/MobileDeviceSharp@234fe5f30cfc0a36385268afd274fbc247879577. Thank you.

**Comment by mveril** [comment]
Ok thank you for the reference From my point of view, it's going in the right direction because it's more consistent with the plist file format itself and I am happy about that. On my side I solve my issue using [UnmanagedType.U8](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedtype) to specify that on the C side the value is of type `uint64_t` even if on my side I use `long` value (`int64`) and it's work perfectly mveril/MobileDeviceSharp@234fe5f30cfc0a36385268afd274fbc247879577. Thank you.

**Comment by nikias** [comment]
The project always suggests to use the latest libplist. It's about the package maintainers that need to update to the latest versions. I am due with a few releases so hopefully they will pick up new versions soon.
