### ISSUE TITLE
About CMake compilation

### ISSUE THREAD

**Issue by AiXanadu** [libimobiledevice/libplist#223]
Could you please provide a CMakeLists.txt file?
CMake can also be configured to be compatible with PKG files.

**Comment by xanadu-lee** [comment]
@nikias @FunkyM @neheb @JonathanBeck 
Will CMake configuration files be considered?

**Comment by neheb** [comment]
I’d love them but probably won’t be merged

**Comment by xanadu-lee** [comment]
What is the reason?
There are many users of CMake or other modern build tools nowadays.
And better support for cross-platform.
