### ISSUE TITLE
git-version-gen breaks configure

### ISSUE THREAD

**Issue by tihmstar** [libimobiledevice/libplist#224]
The `git-version-gen` can print multiple lines in certain circumstances, 
which due to the usage in https://github.com/libimobiledevice/libplist/blob/master/configure.ac#L5 will result in a broken `configure` script.

One way to fix the issue is to make sure only one line is ever returned by the script.
This can be achieved for example by changing:
```
printf %s "$VER"
``` 
to 
```
VER=$(printf %s "$VER" | head -n1)
printf %s "$VER"
```

**Comment by nikias** [comment]
Good catch. Thanks. b8fcc89b74c9128a13b07cc15a0ce25dca0cd97e
