### ISSUE TITLE
Building from released source (zipfile or tar.gz  tarball) is broken by PACKAGE_VERSION issue.

### ISSUE THREAD

**Issue by fduncanh** [libimobiledevice/libplist#228]
```
configure: error: PACKAGE_VERSION is not defined. Make sure to configure a source tree checked out from git or that .tarball-version is present.
```

Not everyone will want to build from a git clone, but might use the release zip or tar files.    Is there a workaround for this PACKAGE_VERSION issue?

**Comment by fduncanh** [comment]
./configure in the

**Comment by nikias** [comment]
Yes, the .tar.bz2 archive is manually uploaded, while the .zip and .tar.gz are automatic links that GitHub posts with the release which is just a plain checkout from git. I am not sure if this is configurable.

**Comment by fduncanh** [comment]
is there any workaround that would allow someone to set PACKAGE_VERSION  when using the automatic github .zip and tar.gz releases (or add some release notes that say not to use them)? Ideally, README.md would address the issue.

In any case, I adapted my own README (which has  a section on building libplist from source in the unlikely event that a package is not available, essentially only macOS users without HomeBrew or MacPorts) to use the tar.bz2 sources

https://github.com/FDH2/UxPlay#building-libplist--200-from-source
