### ISSUE TITLE
No autogen.sh in release file

### ISSUE THREAD

**Issue by My1** [libimobiledevice/libplist#251]
not really much to say except that the readme calls for it, but the release does not have it.

**Comment by mast3rz3ro** [comment]
Hi,

You can compile the release version by directly using `configure.ac` instead of `autogen.sh`

Try this: `./configure`

Please close this issue if your issue is solved.

**Comment by My1** [comment]
if that's the case I would call this a documentation issue and should maybe be added to the readme.

**Comment by mast3rz3ro** [comment]
If you were a familiar with compiling then you wouldn't face this issue, also the readme file in this repo already contains the instructions for building the source code.

Please don't forget to close the issue if your issue is solved.

**Comment by My1** [comment]
I am a bit familiar with it but not all things have asked for ./configure, so I am not sure where to use configure especially if there are instructions attached, might be useful to either make the next release with the sh file or with updated instructions, as not everyone is a professional builder of stuff

**Comment by nikias** [comment]
The readme is referring to building it from source checked out from git, not a source tarball. The release tar.bz indeed doesn't have an autogen.sh as it is in a state that already ran autogen.sh (this is produced using `make dist` or `make distcheck`.

**Comment by My1** [comment]
would it make sense if the readme *inside* the release would mention that.
not sure how many people build this for what I basically just stumbled on this while i was trying to deal with the dependency fun of idevicerestore

**Comment by nikias** [comment]
I figured I should maybe just put the autogen.sh inside the archive...
