### ISSUE TITLE
Issue on Library not loaded: /usr/local/lib/libplist.1.1.10.dylib

### ISSUE THREAD

**Issue by GOBIM** [libimobiledevice/libplist#31]
I am trying to run this and get the following error.
$ios_webkit_debug_proxy
dyld: Library not loaded: /usr/local/lib/libplist.1.1.10.dylib
  Referenced from: /usr/local/bin/ios_webkit_debug_proxy
  Reason: image not found
Trace/BPT trap: 5
Note: I have installed libplist from  $git clone http://git.sukimashita.com/libplist.git
Please suggest me how to fix this? It prevents to start proxy

**Comment by tarunsujit** [comment]
@GOBIM are u able to fix this?

**Comment by kani19** [comment]
is it fixed ?

**Comment by nikias** [comment]
This is not a support forum, and this is not a bug in libplist. The error message already says "image not found" meaning there is no file ```/usr/local/lib/libplist.1.1.10.dylib``` so libplist is not correctly installed. Make sure to compile and install all required libraries and tools from scratch according to the build instructions.
