### ISSUE TITLE
plist_from_bin() crashes trying to access already freed memory

### ISSUE THREAD

**Issue by antonkukoba** [libimobiledevice/libplist#53]
For some reason it tries to copy node data which was already freed. The plist file which causes such behavior can be downloaded here: http://www.filedropper.com/history_2
Environment: windows 7 x86, libplist 1.12 compiled with MS VC.
The problem is not reproduced when running in Debug, since memory data appears to be valid even though it's marked as 'freed'.
The best way to reproduce the problem is to run your application under MS Application Verifier with basic checks.

**Comment by nikias** [comment]
Can you upload the file to a different location? The link you provided seems invalid.

**Comment by antonkukoba** [comment]
Yes, here you go http://s000.tinyupload.com/index.php?file_id=37337952407586518483

**Comment by nikias** [comment]
Fixed in git master.
