### ISSUE TITLE
Support old openstep plist format

### ISSUE THREAD

**Issue by copumpkin** [libimobiledevice/libplist#55]
It's a lot more readable as an output format than the XML plist, and Mac OS can read it just fine. It's even the default format for XCode project specifications, oddly enough!

Not sure if that's a compelling reason to implement a whole other format, but it's a nice format :smile:

**Comment by nikias** [comment]
I kinda like the idea. I should add support for it :)

**Comment by Artoria2e5** [comment]
Let me take a stab at this. No results guaranteed.

**Comment by nikias** [comment]
Latest code has support for this now.
