### ISSUE TITLE
xmlParseMemory   collapse

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libplist#57]
xmlCleanupCharEncodingHandlers();
xmlDictCleanup();
xmlResetLastError();
xmlCleanupGlobals();
xmlCleanupThreads();
xmlCleanupMemory();

Multithreading will collapse

**Comment by nikias** [comment]
I think ```plist_to_xml()``` is generally not to be considered thread-safe.
@FunkyM do you think it is a good idea to use a mutex to make sure ```plist_to_xml``` is only used once at the same time? I think there could also arise an issue with ```setlocale()``` in multi-threaded scenarios.

**Comment by nikias** [comment]
@FunkyM yup, I remembered correctly: https://github.com/UnveN/libplist/commit/4e7caef27b3652eb40f803590ea41c42af6fd9fe

**Comment by cfergeau** [comment]
At the very least, it should not call xmlCleanupThreads(). http://xmlsoft.org/html/libxml-threads.html#xmlCleanupThreads says: «  WARNING: if your application is multithreaded or has plugin support calling this may crash the application if another thread or a plugin is still using libxml2. It's sometimes very hard to guess if libxml2 is in use in the application, some libraries or plugins may use it without notice. In case of doubt abstain from calling this function or do it just before calling exit() to avoid leak reports from valgrind ! » (and there was a bunch of crashes related to that in the past).
I would not be surprised if some of the other xml*Cleanup() methods could have similar side-effects on other threads (which could be spawned by another library) doing unrelated (to libplist) XML processing.

In the same vein, I think setlocale() is global to the process, so it's also fairly rude to change it in a library (think about different thread from an unrelated library doing some locale-dependent stuff at the same time). This seems to be needed for the PLIST_REAL/PLIST_DATE formatting in node_to_xml. glib implements g_ascii_dtostr/g_ascii_formatd when locale-independent strification of a floating point number is needed.

**Comment by nikias** [comment]
This issue was addressed with the recent commit 6ab7e30.
