### ISSUE TITLE
I can't install libplist--mac os

### ISSUE THREAD

**Issue by zcc1414** [libimobiledevice/libplist#58]
./autogen.sh
Configuration for libplist 1.13.0:
-------------------------------------------
  Install prefix: .........: /usr/local
  Python bindings .........: no
  Now type 'make' to build libplist 1.13.0,
  and then 'make install' for installation.

and   
sudo make install
...
libtool: install: ranlib /usr/local/lib/libplist++.a
 /opt/local/bin/gmkdir -p '/usr/local/lib/pkgconfig'
 /opt/local/bin/ginstall -c -m 644 libplist.pc libplist++.pc '/usr/local/lib/pkgconfig'
Making install in include
make[2]: Nothing to be done for `install-exec-am'.
 /opt/local/bin/gmkdir -p '/usr/local/include'
 /opt/local/bin/gmkdir -p '/usr/local/include/plist'
 /opt/local/bin/ginstall -c -m 644  plist/plist.h plist/plist++.h plist/Array.h plist/Boolean.h plist/Data.h plist/Date.h plist/Dictionary.h plist/Integer.h plist/Key.h plist/Node.h plist/Real.h plist/String.h plist/Structure.h plist/Uid.h '/usr/local/include/plist'
Making install in tools
 /opt/local/bin/gmkdir -p '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /opt/local/bin/ginstall -c plistutil '/usr/local/bin'
libtool: install: /opt/local/bin/ginstall -c .libs/plistutil /usr/local/bin/plistutil
make[2]: Nothing to be done for `install-data-am'.
Making install in test
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'. 

libplist is not install in my mac os

**Comment by nikias** [comment]
This looks like a successful installation. Check if you have ```libplist*.dylib``` in ```/usr/local/lib/```

**Comment by zcc1414** [comment]
I  have libplist*.dylib in /usr/local/lib/
ls /usr/local/lib/libplist
libplist++.3.dylib*  libplist++.a         libplist++.dylib@    libplist++.la*       libplist.3.dylib*    libplist.a
but  when I combile libusbmuxd

libusbmuxd git:(master) ✗ ./autogen.sh
....
checking for libplist... no
configure: error: Package requirements (libplist >= 1.11) were not met:

No package 'libplist' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libplist_CFLAGS
and libplist_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

what can I solve the problem?

**Comment by nikias** [comment]
The output already says what to do:
```PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh```

**Comment by FunkyM** [comment]
Closing as the last comment should fix this issue.
Please feel free to report if it didn't help.
