### ISSUE TITLE
More of a feature request than an issue

### ISSUE THREAD

**Issue by darrynza** [libimobiledevice/libplist#61]
Hi, I might just be a little bit lazy, but is there any way you could add in an option tospecify --indir= where one could speficy a directory containing multiple plist files instead of just decalring them one by one ?

Thanks

**Comment by FunkyM** [comment]
Hehe, that is probably too lazy. ;)
While possible it would unfortunately add unnecessary logic.
It's much better (and in my pov. easier) if you use the tool in a loop in some script instead.
