### ISSUE TITLE
Running autogen.sh on Ubuntu 14.04 is okay but running on Windows 7 gives an error

### ISSUE THREAD

**Issue by TerenceAnton** [libimobiledevice/libplist#65]
Hello! I am trying to compile this on Ubuntu and it was okay. But on Windows 7 I get the following error: 
`libtoolize: $pkgltdldir is not a directory: /mingw/share/lib`
`./autogen.sh: line 8: aclocal: command not found`
`./autogen.sh: line 9: autoheader: command not found`
`./autogen.sh: line 10: automake: command not found`
`./autogen.sh: line 11: autoconf: command not found`
`./autogen.sh: line 14: ./configure: No such file or directory`

Am I missing something here? I am new to compiling code in Windows using MinGW

**Comment by nikias** [comment]
Please understand that this is a general question and not a bug. You need to install automake and autoconf for your mingw installation.

**Comment by TerenceAnton** [comment]
Thanks nikias. I was not able to replicate the error anymore. However I was able to get this error: 
`./configure: line 15289: syntax error near unexpected token libxml2,`
`./configure: line 15289: PKG_CHECK_MODULES(libxml2, libxml-2.0 >= $LIBXML2_VERS
ION)`

**Comment by sepsky** [comment]
@tobeedelafuente quite late to this, but did you find out how to fix your issue you had? Thanks :)
