### ISSUE TITLE
libplist can't compile

### ISSUE THREAD

**Issue by cusmire** [libimobiledevice/libplist#66]
Hello guy!
When I try to install idevicerestore, it says libplist 1,12 is require but I have 1.10 installed, I try to change the file configure.ac by change it to libplist PKG_CHECK_MODULES(libplist, libplist >= 1.10),it seems bypass this error but still not compiling. I Finally realize that I should intall the 1.12 version of libplist. when i try it gives me this error: 
checking whether byte ordering is bigendian... no
checking whether to enable WIN32 build settings... no
checking for a Python interpreter with version >= 2.3... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for cython... no
configure: WARNING: cannot find 'cython' program. You should look at http://www.cython.org or install your distribution specific cython package.
checking for python2.7... (cached) /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... yes
checking for Python include path... ./configure: line 16698: type: /usr/bin/python-config: not found
-I/usr/include/python2.7
checking for Python library path... ./configure: line 16718: type: /usr/bin/python-config: not found
-L/usr/lib/python2.7 -lpython2.7
checking for Python site-packages path... /usr/lib/python2.7/dist-packages
checking python extra libraries... ('-L/usr/lib -lz', '-lpthread -ldl  -lutil')
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... no
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================
Thank you for your coming help

**Comment by cusmire** [comment]
Ok guy! it's ok. I simply done this by doing this. sudo apt-get install python-dev.

**Comment by nikias** [comment]
You can also run configure with --without-cython.

**Comment by urherenow** [comment]
I know this is old and long closed, but I just spent hours trying to figure this stuff out myself. I feel stupid now. Everything you need is in the Cygwin setup, you just have to pick the correct things to install. Such as "python-devel" <-- this fixes your last error

There are also cython packages in there to choose from.
