### ISSUE TITLE
 plist_get_uint_val: Assertion `length == sizeof(uint64_t)' failed.

### ISSUE THREAD

**Issue by gitsop01** [libimobiledevice/libplist#70]
During a springboard access on ipad recieved this error.

**Comment by gitsop01** [comment]
This function is called several times from sbmanager device.c code and fails on ipad and iphone 5 
access.

**Comment by nikias** [comment]
Would be good to have a sample plist file to test this particular issue.

**Comment by gitsop01** [comment]
This is no longer an issue  with the lastest git head code available.
