### ISSUE TITLE
How to complie the Source code with Visual Studio?

### ISSUE THREAD

**Issue by lianzisong** [libimobiledevice/libplist#77]
I want to complie the source code with visual studio ,but it seems that the project can not support my idear ,can anyone can help me ? or tell me how to complie it through the Cygwin? It seems that it need so many depend libs.

**Comment by nikias** [comment]
Visual Studio building is not officially supported.

**Comment by qmfrederik** [comment]
That said, if you go to https://github.com/libimobiledevice-win32/libplist/, you'll find a fork of the project which you can use to build with Visual Studio.
