### ISSUE TITLE
The latest libplist make idevicerestore errors [ipsw_get_latest_fw: ERROR: Can't find MobileDeviceSoftwareVersionsByVersion dict in version data]

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libplist#80]
The latest libplist make idevicerestore errors, when using -l to download latest firmware
[ipsw_get_latest_fw: ERROR: Can't find MobileDeviceSoftwareVersionsByVersion dict in version data

**Comment by jackczhang** [comment]
looks like the libplist does not handle the situation below
</dict><key>iTunesWindowsDoNotUseASU</key>
which '><' connected.

**Comment by jackczhang** [comment]
Attached latest version.xml
[version.zip](https://github.com/libimobiledevice/libplist/files/612877/version.zip)

**Comment by nikias** [comment]
thanks, will take a look

**Comment by nikias** [comment]
Fixed with commit https://github.com/libimobiledevice/libplist/commit/5e8fb617b8f7857693e7b41f56eaa6767ed6a54d
