### ISSUE TITLE
Issue a release

### ISSUE THREAD

**Issue by grahamc** [libimobiledevice/libplist#96]
Hello @nikias!

You've put in a ton of great, great work in to libplist lately. Thank you.

As part of the weekly NixOS bug hunt (https://github.com/NixOS/nixpkgs/issues/22549) I was about to apply 3a55ddd3c4c11ce75a86afbefd085d8d397ff957 as a patch over top 1.12, but found it doesn't apply cleanly. Digging around the repo, I've seen just how much you have done lately. It shows me there are many more fixes than just that one commit.

Do you have a plan for when your next release will be? Will it be API-compatible with 1.12?

Thank you again,
Graham Christensen

**Comment by nikias** [comment]
A release is close, working on ironing out a few remaining issues.
It will be API compatible with 1.12, yes.

**Comment by grahamc** [comment]
Thank you so much, glad to hear. Is there something I can do to help?

**Comment by nikias** [comment]
Released 2.0.0
