### ISSUE TITLE
Read me please.

### ISSUE THREAD

**Issue by Manu70319** [libimobiledevice/libplist#97]
Hey! I had a problem exactly like this:
$ios_webkit_debug_proxy
dyld: Library not loaded: /usr/local/lib/libplist.1.1.10.dylib
Referenced from: /usr/local/bin/ios_webkit_debug_proxy
Reason: image not found
Trace/BPT trap: 5

and did everything necessary to fix it and did exactly what IDevice central did: https://www.youtube.com/watch?v=Y9iPE7XIQtU

But now I have another error:

dyld: Library not loaded: /usr/local/lib/libplist.3.dylib
  Referenced from: /Users/manueltugentman/Desktop/downgrade/futurerestore_osx
  Reason: image not found
Abort trap: 6

**Comment by nikias** [comment]
Sorry, this is not a bug in libplist. This is usual compilation and installation of libraries. You can just google how this works. Also, what is so hard to understand about
```dyld: Library not loaded: /usr/local/lib/libplist.3.dylib``` ? It literally tells you what's wrong.
